### ISSUE TITLE
Dynamic bin count rather than hard coded

### ISSUE THREAD

**Issue by willeppy** [cmudig/AutoProfile#26]
Right now is hard coded number of bins for Q and T, would be nice to have it done dynamically so adjusts to the data

See https://observablehq.com/@d3/d3-bin for reference

**Comment by domoritz** [comment]
Unless you have specific ideas, you can use Scott's normal rule and cap to 200 for reasonable outputs. Or you just set a somewhat larger number than the current resolution. The problem with Scott's rule its that it make distributional assumptions.
